version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/swift"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/mcp"
    schedule:
      interval: "weekly"
