import Foundation

public enum SpeakerMapper {
    public static func assignSpeakers(to segments: [Segment], from turns: [Turn]) -> [Segment] {
        segments.map { seg in
            var best = "UNKNOWN"; var bestOverlap = 0.0
            for turn in turns {
                let overlap = max(0, min(seg.end, turn.end) - max(seg.start, turn.start))
                if overlap > bestOverlap { bestOverlap = overlap; best = turn.speaker }
            }
            return Segment(start: seg.start, end: seg.end, text: seg.text, speaker: best)
        }
    }

    /// Returns each detected speaker label once, ordered by that speaker's
    /// earliest segment start time in the audio. Deliberately independent
    /// of SpeakerKit's own raw label values, so "the first speaker to
    /// talk" means the same thing here as it does for the Python backend
    /// (whose pyannote.audio-based labels come from clustering-internal
    /// cluster indices, not chronological order).
    public static func speakersByFirstAppearance(segments: [Segment]) -> [String] {
        var seen = Set<String>()
        var order: [String] = []
        for seg in segments.sorted(by: { $0.start < $1.start }) where !seen.contains(seg.speaker) {
            seen.insert(seg.speaker)
            order.append(seg.speaker)
        }
        return order
    }

    /// Maps speaker labels to caller-supplied names in order, e.g.
    /// orderedLabels[0] -> names[0]. Extra names beyond orderedLabels.count
    /// are ignored; fewer names than detected speakers leaves the
    /// remainder unmapped, for the caller to merge over an
    /// existing/default mapping.
    public static func assignNames(detected orderedLabels: [String], names: [String]) -> [String: String] {
        Dictionary(uniqueKeysWithValues: zip(orderedLabels, names))
    }

    public static func coalesce(segments: [Segment], mapping: [String: String]) -> [Block] {
        var blocks: [Block] = []
        for seg in segments {
            let text = seg.text.trimmingCharacters(in: .whitespaces)
            guard !text.isEmpty else { continue }
            let name = mapping[seg.speaker] ?? seg.speaker
            if blocks.last?.speaker == name {
                blocks[blocks.count - 1].text += " " + text
            } else {
                blocks.append(Block(speaker: name, start: seg.start, text: text))
            }
        }
        return blocks
    }

    public static func loadMapping(from url: URL) -> [String: String] {
        guard let data = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        return json.compactMapValues { $0 as? String }.filter { !$0.key.hasPrefix("_") }
    }

    public static func saveMapping(_ mapping: [String: String], to url: URL) throws {
        var payload: [String: Any] = ["_comment": "Speaker mapping generated by DiarizeKit."]
        for (k, v) in mapping.sorted(by: { $0.key < $1.key }) { payload[k] = v }
        let data = try JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: url)
    }
}
