import Foundation

public enum SpeakerMapper {
    public static func assignSpeakers(to segments: [Segment], from turns: [Turn]) -> [Segment] {
        segments.map { seg in
            var best = "UNKNOWN"; var bestOverlap = 0.0
            for turn in turns {
                let overlap = max(0, min(seg.end, turn.end) - max(seg.start, turn.start))
                if overlap > bestOverlap { bestOverlap = overlap; best = turn.speaker }
            }
            return Segment(start: seg.start, end: seg.end, text: seg.text, speaker: best)
        }
    }

    public static func coalesce(segments: [Segment], mapping: [String: String]) -> [Block] {
        var blocks: [Block] = []
        for seg in segments {
            let text = seg.text.trimmingCharacters(in: .whitespaces)
            guard !text.isEmpty else { continue }
            let name = mapping[seg.speaker] ?? seg.speaker
            if blocks.last?.speaker == name {
                blocks[blocks.count - 1].text += " " + text
            } else {
                blocks.append(Block(speaker: name, start: seg.start, text: text))
            }
        }
        return blocks
    }

    public static func loadMapping(from url: URL) -> [String: String] {
        guard let data = try? Data(contentsOf: url),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        return json.compactMapValues { $0 as? String }.filter { !$0.key.hasPrefix("_") }
    }

    public static func saveMapping(_ mapping: [String: String], to url: URL) throws {
        var payload: [String: Any] = ["_comment": "Speaker mapping generated by DiarizeKit."]
        for (k, v) in mapping.sorted(by: { $0.key < $1.key }) { payload[k] = v }
        let data = try JSONSerialization.data(withJSONObject: payload, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: url)
    }
}
